# Generated by Django 5.0 on 2023-12-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('id_proof', models.CharField(max_length=20)),
                ('account_type', models.CharField(max_length=10)),
                ('email_address', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('residential_address', models.TextField()),
                ('digital_picture', models.ImageField(upload_to='digital_pictures/')),
                ('citizenship', models.CharField(max_length=50)),
                ('initial_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agree_t_and_c', models.BooleanField()),
            ],
        ),
    ]
