# Generated by Django 5.0 on 2023-12-28 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybank_app', '0003_remove_bankaccount_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='initial_deposit',
        ),
    ]
