# Generated by Django 5.0 on 2023-12-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybank_app', '0004_remove_bankaccount_initial_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='agree_t_and_c',
        ),
    ]
