# Generated by Django 5.0 on 2023-12-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank_app', '0005_remove_bankaccount_agree_t_and_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
