# Generated by Django 5.0 on 2023-12-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account')], max_length=10),
        ),
    ]
