# Generated by Django 5.0 on 2023-12-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybank_app', '0002_alter_bankaccount_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='digital_picture',
        ),
    ]
