# Generated by Django 5.0 on 2024-01-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank_app', '0003_remove_bankaccount_digital_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
