# Generated by Django 4.2.8 on 2023-12-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(choices=[('jaipur', 'jaipur'), ('Jodhpur', 'Jodhpur'), ('Kota', 'Kota')], max_length=100)),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
    ]
