# Generated by Django 4.2.8 on 2023-12-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arthonsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='city',
            field=models.CharField(choices=[('Jaipur', 'Jaipur'), ('Jodhpur', 'Jodhpur'), ('Kota', 'Kota')], max_length=100),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='skill',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('javascript', 'javascript'), ('C++', 'C++')], max_length=100),
        ),
    ]
